# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'final.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLabel, QMainWindow, QFileDialog
from PyQt5.QtCore import QTimer
import subprocess
import sys
import os

file_path = ""


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(638, 646)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Menu = QtWidgets.QWidget(self.centralwidget)
        self.Menu.setStyleSheet("QWidget{\n"
"    background-color: rgb(39, 42, 80);\n"
"}\n"
"\n"
"QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    text-align : left;\n"
"    height : 30px;\n"
"    border : none;\n"
"    padding-left : 15px;\n"
"    padding-top : 15px;\n"
"    padding-bottom : 15px;\n"
"    padding-right : 0px;\n"
"    margin-right : 0px;\n"
"    border-top-left-radius : 8px;\n"
"    border-bottom-left-radius : 8px\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    color: rgb(0, 0, 76);\n"
"    background-color: rgb(170, 255, 0);\n"
"    font-weight : bold;\n"
"}\n"
"\n"
"QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"    text-align : center;\n"
"}")
        self.Menu.setObjectName("Menu")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Menu)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.Menu)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(9, 45, 10, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.verticalLayout_2.addWidget(self.frame_2, 0, QtCore.Qt.AlignTop)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setContentsMargins(-1, 9, 0, -1)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setContentsMargins(9, 40, 0, -1)
        self.verticalLayout_4.setSpacing(15)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("")
        self.pushButton_4.setCheckable(True)
        self.pushButton_4.setAutoExclusive(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_4.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setCheckable(True)
        self.pushButton_5.setAutoExclusive(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_4.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setCheckable(True)
        self.pushButton_6.setAutoExclusive(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_4.addWidget(self.pushButton_6)
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setCheckable(True)
        self.pushButton_11.setAutoExclusive(True)
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_4.addWidget(self.pushButton_11)
        self.verticalLayout_5.addWidget(self.frame_4, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout.addWidget(self.Menu)
        self.MainBody = QtWidgets.QWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.MainBody.setFont(font)
        self.MainBody.setStyleSheet("QWidget{\n"
"    background-color: rgb(53, 57, 97);\n"
"}\n"
"QLabel{\n"
"    color:white;\n"
"}")
        self.MainBody.setObjectName("MainBody")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.MainBody)
        self.verticalLayout_6.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_5 = QtWidgets.QFrame(self.MainBody)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setStyleSheet("")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_7.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(0, 170))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.page)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_12 = QtWidgets.QFrame(self.page)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_6.addWidget(self.frame_12)
        self.stackedWidget.addWidget(self.page)
        self.partie1_page = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.partie1_page.sizePolicy().hasHeightForWidth())
        self.partie1_page.setSizePolicy(sizePolicy)
        self.partie1_page.setStyleSheet("QFrame{\n"
"width:60px\n"
"}")
        self.partie1_page.setObjectName("partie1_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.partie1_page)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_7 = QtWidgets.QFrame(self.partie1_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_7.setStyleSheet("")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_3.setContentsMargins(-1, 9, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_3.addWidget(self.frame_7)
        self.frame_14 = QtWidgets.QFrame(self.partie1_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_14.sizePolicy().hasHeightForWidth())
        self.frame_14.setSizePolicy(sizePolicy)
        self.frame_14.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_14.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_14.setSizeIncrement(QtCore.QSize(0, 100))
        self.frame_14.setBaseSize(QtCore.QSize(0, 500))
        self.frame_14.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 76);\n"
"    background-color: rgb(170, 255, 0);\n"
"    padding : 5px;\n"
"    border-radius : 10px;\n"
"    font-size:10px\n"
"}\n"
"QRadioButton{\n"
"    Color :white\n"
"}\n"
"")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setMidLineWidth(0)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_8.setSpacing(9)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_6 = QtWidgets.QFrame(self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 170))
        self.frame_6.setStyleSheet("*{\n"
"    background-color: rgb(79, 83, 118);\n"
"}\n"
"QFrame{\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton{\n"
"    color: rgb(0, 0, 76);\n"
"    background-color: rgb(240, 240, 240);\n"
"    padding : 5px;\n"
"    border-radius : 10px;\n"
"    font-size : 14px;\n"
"    width:120px;\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_2 = QtWidgets.QLabel(self.frame_6)
        self.label_2.setGeometry(QtCore.QRect(10, 0, 371, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.layoutWidget = QtWidgets.QWidget(self.frame_6)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 40, 191, 111))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_13.setContentsMargins(0, 10, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.radioButton = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_13.addWidget(self.radioButton)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(10, 0))
        self.pushButton.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.pushButton.clicked.connect(self.Upload_Image_Part1)

        self.verticalLayout_13.addWidget(self.pushButton, 0, QtCore.Qt.AlignHCenter)
        self.radioButton_2 = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_13.addWidget(self.radioButton_2)
        self.verticalLayout_8.addWidget(self.frame_6)
        self.frame_13 = QtWidgets.QFrame(self.frame_14)
        self.frame_13.setMinimumSize(QtCore.QSize(0, 270))
        self.frame_13.setStyleSheet("*{\n"
"    background-color: rgb(79, 83, 118);\n"
"}\n"
"QFrame{\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QComboBox {\n"
"    background-color: #f0f0f0;      /* Light background */\n"
"    border: 1px solid #b0b0b0;      /* Subtle border */\n"
"    border-radius: 5px;             /* Rounded corners */\n"
"    padding: 5px 10px;              /* Spacing inside */\n"
"    font-size: 14px;                /* Text size */\n"
"    color: #333;                    /* Text color */\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 1px solid #0078d7;      /* Highlight border on hover */\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px;                    /* Size of the dropdown arrow */\n"
"    border-left: 1px solid #b0b0b0; /* Separator between text and arrow */\n"
"    background-color: #e0e0e0;      /* Dropdown background */\n"
"    border-top-right-radius: 5px;\n"
"    border-bottom-right-radius: 5px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(\"C:/Users/HP/Documents/Studies/Master2/VISION/Projet Vision/images/down.png\");\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid #b0b0b0;      /* Border for dropdown items */\n"
"    background-color: #ffffff;      /* Background for dropdown items */\n"
"    selection-background-color: #0078d7;  /* Highlighted item background */\n"
"    selection-color: #ffffff;       /* Highlighted item text color */\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.label_7 = QtWidgets.QLabel(self.frame_13)
        self.label_7.setGeometry(QtCore.QRect(10, 0, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.layoutWidget1 = QtWidgets.QWidget(self.frame_13)
        self.layoutWidget1.setGeometry(QtCore.QRect(40, 40, 191, 191))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_11.setContentsMargins(0, 10, 0, 0)
        self.verticalLayout_11.setSpacing(6)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_11.addWidget(self.label_10)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox.setMaximumSize(QtCore.QSize(170, 16777215))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_11.addWidget(self.comboBox)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_11.addWidget(self.label_9)
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_2.setMaximumSize(QtCore.QSize(170, 16777215))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.verticalLayout_11.addWidget(self.comboBox_2)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_11.addWidget(self.label_16)
        self.comboBox_3 = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_3.setMaximumSize(QtCore.QSize(170, 16777215))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.verticalLayout_11.addWidget(self.comboBox_3)
        self.verticalLayout_8.addWidget(self.frame_13)
        self.frame_15 = QtWidgets.QFrame(self.frame_14)
        self.frame_15.setMinimumSize(QtCore.QSize(0, 70))
        self.frame_15.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 76);\n"
"    background-color: rgb(240, 240, 240);\n"
"    padding : 5px;\n"
"    border-radius : 10px;\n"
"    font-size : 14px;\n"
"}")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_15)
        self.pushButton_2.setMinimumSize(QtCore.QSize(30, 0))
        self.pushButton_2.setMaximumSize(QtCore.QSize(150, 30))
        self.pushButton_2.setObjectName("pushButton_2")

        self.pushButton_2.clicked.connect(self.On_Click_Part1)
        
        self.horizontalLayout_7.addWidget(self.pushButton_2)
        self.verticalLayout_8.addWidget(self.frame_15, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_3.addWidget(self.frame_14)
        self.stackedWidget.addWidget(self.partie1_page)
        self.partie2_page = QtWidgets.QWidget()
        self.partie2_page.setObjectName("partie2_page")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.partie2_page)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_8 = QtWidgets.QFrame(self.partie2_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_4.setContentsMargins(-1, 11, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_9.addWidget(self.frame_8, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.frame_9 = QtWidgets.QFrame(self.partie2_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.frame_21 = QtWidgets.QFrame(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_21.sizePolicy().hasHeightForWidth())
        self.frame_21.setSizePolicy(sizePolicy)
        self.frame_21.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 76);\n"
"    background-color: rgb(240, 240, 240);\n"
"    padding : 5px;\n"
"    padding-right : 20px;\n"
"    padding-left : 20px;\n"
"    border-radius : 8px;\n"
"    font-size : 14px;\n"
"}")
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_21)
        self.pushButton_10.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_10.setMaximumSize(QtCore.QSize(200, 40))
        self.pushButton_10.setObjectName("pushButton_10")

        self.pushButton_10.clicked.connect(self.run_calibrate)

        self.horizontalLayout_10.addWidget(self.pushButton_10)
        self.verticalLayout_18.addWidget(self.frame_21)
        self.frame_22 = QtWidgets.QFrame(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_22.sizePolicy().hasHeightForWidth())
        self.frame_22.setSizePolicy(sizePolicy)
        self.frame_22.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_22.setMaximumSize(QtCore.QSize(16777215, 300))
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.textEdit = QtWidgets.QTextEdit(self.frame_22)
        self.textEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 300))
        self.textEdit.setStyleSheet("QTextEdit{\n"
"    background-color: rgb(240, 240, 240);\n"
"    border-radius:10px\n"
"}")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_19.addWidget(self.textEdit)
        self.verticalLayout_18.addWidget(self.frame_22)
        self.verticalLayout_9.addWidget(self.frame_9)
        self.stackedWidget.addWidget(self.partie2_page)

        self.partie3_page = QtWidgets.QWidget()
        self.partie3_page.setObjectName("partie3_page")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.partie3_page)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_10 = QtWidgets.QFrame(self.partie3_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_5.setContentsMargins(-1, 11, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_10.addWidget(self.frame_10, 0, QtCore.Qt.AlignTop)
        self.frame_11 = QtWidgets.QFrame(self.partie3_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_11.sizePolicy().hasHeightForWidth())
        self.frame_11.setSizePolicy(sizePolicy)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_23 = QtWidgets.QFrame(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_23.sizePolicy().hasHeightForWidth())
        self.frame_23.setSizePolicy(sizePolicy)
        self.frame_23.setMinimumSize(QtCore.QSize(0, 130))
        self.frame_23.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_23.setStyleSheet("*{\n"
"    background-color: rgb(79, 83, 118);\n"
"}\n"
"QFrame{\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton{\n"
"    color: rgb(0, 0, 76);\n"
"    background-color: rgb(240, 240, 240);\n"
"    padding : 5px;\n"
"    padding-right : 20px;\n"
"    padding-left : 20px;\n"
"    border-radius : 8px;\n"
"    margin-left : 60px;\n"
"    font-size : 14px;\n"
"}\n"
"QRadioButton{\n"
"    color:white;\n"
"    margin-left : 20px\n"
"}")
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.layoutWidget2 = QtWidgets.QWidget(self.frame_23)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 0, 361, 111))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_20.setContentsMargins(0, 6, 0, 0)
        self.verticalLayout_20.setSpacing(15)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_17 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("Qlabel{\n"
"    margin-top : 15px,\n"
"}")
        self.label_17.setObjectName("label_17")
        self.verticalLayout_20.addWidget(self.label_17)
        self.radioButton_3 = QtWidgets.QRadioButton(self.layoutWidget2)
        self.radioButton_3.setStyleSheet("QRadioButton{\n"
"    margin-bottom : 10px;\n"
"}")
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout_20.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.layoutWidget2)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout_20.addWidget(self.radioButton_4)
        self.verticalLayout_12.addWidget(self.frame_23)
        self.frame_16 = QtWidgets.QFrame(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_16.sizePolicy().hasHeightForWidth())
        self.frame_16.setSizePolicy(sizePolicy)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_11.setSpacing(10)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_12.sizePolicy().hasHeightForWidth())
        self.pushButton_12.setSizePolicy(sizePolicy)
        self.pushButton_12.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_12.setMaximumSize(QtCore.QSize(200, 40))
        self.pushButton_12.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 76);\n"
"    background-color: rgb(240, 240, 240);\n"
"    padding : 5px;\n"
"    border-radius : 8px;\n"
"    font-size : 14px;\n"
"    width:700px;\n"
"    margin-left : 62px;\n"
"}")
        self.pushButton_12.setObjectName("pushButton_12")

        self.pushButton_12.clicked.connect(self.run_partie3)

        self.horizontalLayout_11.addWidget(self.pushButton_12)
        self.verticalLayout_12.addWidget(self.frame_16, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_10.addWidget(self.frame_11)
        self.stackedWidget.addWidget(self.partie3_page)
        self.Amelioration_page = QtWidgets.QWidget()
        self.Amelioration_page.setObjectName("Amelioration_page")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.Amelioration_page)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_17 = QtWidgets.QFrame(self.Amelioration_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_17.sizePolicy().hasHeightForWidth())
        self.frame_17.setSizePolicy(sizePolicy)
        self.frame_17.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.frame_17)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.verticalLayout_14.addWidget(self.frame_17, 0, QtCore.Qt.AlignHCenter)
        self.frame_18 = QtWidgets.QFrame(self.Amelioration_page)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.widget = QtWidgets.QWidget(self.frame_18)
        self.widget.setGeometry(QtCore.QRect(20, 30, 774, 131))
        self.widget.setObjectName("widget")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(20)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_8 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_15.addWidget(self.label_8)
        self.label_11 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_15.addWidget(self.label_11)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_3.setMaximumSize(QtCore.QSize(300, 40))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 76);\n"
"    background-color: rgb(240, 240, 240);\n"
"    padding : 5px;\n"
"    border-radius : 8px;\n"
"    font-size : 14px;\n"
"    width:700px;\n"
"    margin-left : 62px;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")

        self.pushButton_3.clicked.connect(self.run_partie4)

        self.verticalLayout_15.addWidget(self.pushButton_3)
        self.verticalLayout_14.addWidget(self.frame_18)
        self.stackedWidget.addWidget(self.Amelioration_page)
        self.verticalLayout_7.addWidget(self.stackedWidget)
        self.verticalLayout_6.addWidget(self.frame_5, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout.addWidget(self.MainBody)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def Upload_Image_Part1(self):
        # Open file dialog to select an image
        global file_path
        file_path, _ = QFileDialog.getOpenFileName(
            None, 
            "Select Image", 
            "", 
            "Images (*.png *.xpm *.jpg *.jpeg *.bmp)"
        )
        if file_path:  # If a file is selected
            print(file_path)
        else:
            print("No image selected!")

    def On_Click_Part1(self):
        selected_value = None

        #get detection parameteres
        if self.radioButton.isChecked():
            selected_value = self.radioButton.text()
        elif self.radioButton_2.isChecked():
            selected_value = self.radioButton_2.text()

        if selected_value:
            print(f"You selected: {selected_value}")
        else:
            print("Please select an option!")

        #Get Object Color
        object_color = self.comboBox.currentText()
        
        #Get object shape
        object_shape = self.comboBox_2.currentText()

        #Get class object
        object_class = self.comboBox_3.currentText()

        print(f"You selected: {object_color}")
        print(f"You selected: {object_shape}")
        print(f"You selected: {object_class}")

        print(file_path)

        # Start the subprocess
        if(selected_value.strip() == "à partir d'une image"):
            print("true")
            try:
                subprocess.Popen([sys.executable, "partie1_OpenCV.py", object_color, object_shape, file_path])
            except FileNotFoundError:
                QtWidgets.QMessageBox.critical(
                    None, "Error", "File 'partie1_OpenCV.py' not found!"
                )
                return
        elif(selected_value.strip() == "en temps réel"):
            print("yes")
            try:
                subprocess.Popen([sys.executable, "partie1_Real Time_YoloV5.py", object_class])
            except FileNotFoundError:
                QtWidgets.QMessageBox.critical(
                    None, "Error", "File 'detecter_Objet_OpenCV.py' not found!"
                )
                return
    
   
    def run_partie3(self):
        selected_value = None

        #get detection parameteres
        if self.radioButton_3.isChecked():
            selected_value = self.radioButton_3.text()
        elif self.radioButton_4.isChecked():
            selected_value = self.radioButton_4.text()

        if selected_value:
            print(f"You selected: {selected_value}")
        else:
            print("Please select an option!")

        if(selected_value=="Objet en mouvement avec des caméras fixes"):
            try:
                subprocess.Popen([sys.executable, "partie3_CamerasFix_ObjetMouv.py"])
            except FileNotFoundError:
                QtWidgets.QMessageBox.critical(
                    None, "Error", "File 'partie3_CamerasFix_ObjetMouv.py' not found!"
                )
                return
        elif(selected_value=="Objet fixe avec des caméras en mouvement"):
            try:
                subprocess.Popen([sys.executable, "partie3_CamerasMouv_ObjetFix.py"])
            except FileNotFoundError:
                QtWidgets.QMessageBox.critical(
                    None, "Error", "File 'partie3_CamerasMouv_ObjetFix.py' not found!"
                )
                return

    def run_partie4(self):
        try:
            subprocess.Popen([sys.executable, "partie4_Amelioration.py"])
        except FileNotFoundError:
            QtWidgets.QMessageBox.critical(
                None, "Error", "File 'partie4_Amelioration.py' not found!"
            )
            return

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Menu Principal"))
        self.pushButton_4.setText(_translate("MainWindow", "Partie1"))
        self.pushButton_5.setText(_translate("MainWindow", "Partie2"))
        self.pushButton_6.setText(_translate("MainWindow", "Partie3"))
        self.pushButton_11.setText(_translate("MainWindow", "Amélioration"))
        self.label_3.setText(_translate("MainWindow", "Partie 1 : Détection d\'Objet"))
        self.label_2.setText(_translate("MainWindow", "Option de détection"))
        self.radioButton.setText(_translate("MainWindow", "à partir d\'une image "))
        self.pushButton.setText(_translate("MainWindow", "Charger l\'image"))
        self.radioButton_2.setText(_translate("MainWindow", "en temps réel"))
        self.label_7.setText(_translate("MainWindow", "Caractéristiques de l\'ojet à détecter"))
        self.label_10.setText(_translate("MainWindow", "Couleur de l\'objet"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Couleur"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Orange"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Bleu"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Rouge"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Vert"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Jaune"))
        self.label_9.setText(_translate("MainWindow", "Forme de l\'objet"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Forme"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Carre"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Rectangle"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Cercle"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "Triangle"))
        self.label_16.setText(_translate("MainWindow", "Class de l\'objet"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Bottle"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Orange"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "Book"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "Bear"))
        self.pushButton_2.setText(_translate("MainWindow", "Lancer la detection"))
        self.label_4.setText(_translate("MainWindow", "Partie 2 : Calibration de Caméra"))
        self.pushButton_10.setText(_translate("MainWindow", "Commencer la calibration"))
        self.label_5.setText(_translate("MainWindow", "Partie 3 : Calcul de Position de Distance"))
        self.label_17.setText(_translate("MainWindow", "Choix de la Configuration"))
        self.radioButton_3.setText(_translate("MainWindow", "Objet fixe avec des caméras en mouvement"))
        self.radioButton_4.setText(_translate("MainWindow", "Objet en mouvement avec des caméras fixes"))
        self.pushButton_12.setText(_translate("MainWindow", "Lancer"))
        self.label_6.setText(_translate("MainWindow", "Partie 4 : Amélioration"))
        self.label_8.setText(_translate("MainWindow", "L’estimation de trajectoire et de distance pour la"))
        self.label_11.setText(_translate("MainWindow", "reconstruction et la reprojection 3D"))
        self.pushButton_3.setText(_translate("MainWindow", "Commencer La détection"))


    def run_calibrate(self):
        try:
            self.textEdit.clear()  # Clear previous results
            self.calibration_thread = CalibrationThread()
            self.calibration_thread.output_signal.connect(self.display_output)
            self.calibration_thread.finished.connect(self.load_results)
            self.calibration_thread.start()
        except Exception as e:
            self.textEdit.setText(f"Erreur lors de l'exécution : {e}")

    def display_output(self, output):
        current_text = self.textEdit.toPlainText()
        new_text = current_text + "\n" + output
        self.textEdit.setPlainText(new_text)
        cursor = self.textEdit.textCursor()
        cursor.movePosition(QtGui.QTextCursor.End)
        self.textEdit.setTextCursor(cursor)

    def load_results(self):
        try:
            with open("calibration_results.txt", "r") as file:
                calibration_results = file.read()
            formatted_results = f"""
<b>1. Matrice de la Caméra :</b><br>
{self.format_matrix(calibration_results, "Camera Matrix")}

<b>2. Coefficients de Distorsion :</b><br>
{self.format_matrix(calibration_results, "Distortion Coefficients")}

<b>4. Vecteurs de Rotation (par image) :</b><br>
{self.format_vectors(calibration_results, "Rotation Vectors")}

<b>5. Vecteurs de Translation (par image) :</b><br>
{self.format_vectors(calibration_results, "Translation Vectors")}
"""
            self.textEdit.setHtml(formatted_results)
        except Exception as e:
            self.textEdit.setText(f"Erreur lors du chargement des résultats : {e}")

    def format_matrix(self, text, title):
        start = text.find(title)
        if start == -1:
            return "Non disponible"
        end = text.find("\n\n", start)
        matrix_text = text[start + len(title) + 2:end].strip()
        return f"<pre>{matrix_text}</pre><br>"

    def format_vectors(self, text, title):
        start = text.find(title)
        if start == -1:
            return "Non disponible"
        end = text.find("\n\n", start)
        vectors_text = text[start + len(title):end].strip()
        formatted_vectors = "<br>".join(vectors_text.splitlines())
        return f"<pre>{formatted_vectors}</pre><br>"
    
class CalibrationThread(QtCore.QThread):
    output_signal = QtCore.pyqtSignal(str)  # Signal pour transmettre les messages de sortie

    def run(self):
        """Exécuter le script et transmettre les sorties en temps réel."""
        try:
            process = subprocess.Popen(
                ["python", "-u", "partie2_Callibrage.py"],  # -u pour désactiver le buffering
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                bufsize=1  # Forcer le mode ligne par ligne
            )
            while True:
                output = process.stdout.readline()
                if output == "" and process.poll() is not None:
                    break
                if output:
                    self.output_signal.emit(output.strip())
            stderr = process.stderr.read()
            if stderr:
                self.output_signal.emit(f"Erreur : {stderr.strip()}")
        except Exception as e:
            self.output_signal.emit(f"Erreur lors de l'exécution : {e}")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())